export const SET_MEAN_ARRIVAL_TIME = 'SET_MEAN_ARRIVAL_TIME';
export const SET_MEAN_CONE_MAKING_TIME = 'SET_MEAN_CONE_MAKING_TIME';
export const SET_MEAN_WORK_MINUTES = 'SET_MEAN_WORK_MINUTES';
export const SET_NUMBER_SIMULATIONS = 'SET_NUMBER_SIMULATIONS';

export const INITIATE_NEW_SIMULATION = 'INITIATE_NEW_SIMULATION';
export const INITIATE_NEW_SIMULATION_SUCCESS = 'INITIATE_NEW_SIMULATION_SUCCESS';
export const INITIATE_NEW_SIMULATION_FAILURE = 'INITIATE_NEW_SIMULATION_FAILURE';

export const CLEAR_DATA_FROM_STORE = 'CLEAR_DATA_FROM_STORE';
export const PERSIST_DATA_TO_STORE = 'PERSIS_DATA_TO_STORE';
